/**
 * @File Name          : myComponentController.cls
 * @Description        :
 * @Author             : Advait Yermalkar
 * @Group              :
 * @Last Modified By   : Advait Yermalkar
 * @Last Modified On   : 2/27/2020, 6:02:32 AM
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    2/27/2020   Advait Yermalkar     Initial Version
**/
public class myComponentController {

}